---
:consumer_key: mJ5otbhPGNoDCgCL7j5g
:consumer_secret: M0XkT6GeBnjxdlWHcSGYX1JutMVS9D5ISlkqRfShg
:access_token: 4005921988-0pZqrVrL72763CtdkBULXnouFg48JrSNIUv1ZV3
:access_token_secret: EVQdRaYu5rd6UAuouGWc8Iz2iYZtQ8h9b0Cx8lAN6vVoA
